### ISSUE TITLE
llm_bench requirements.txt / environment setup is broken

### ISSUE THREAD

**Issue by ngaloppo** [openvinotoolkit/openvino.genai#163]
auto-gptq can't be installed due to a build error:

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gx/znq60x355475d1njb709q0jh0000gn/T/pip-install-2tmqwfxi/auto-gptq_3c9ac5ea4a8f4b049c9ff044cc750c38/setup.py", line 58, in <module>
          CUDA_VERSION = "".join(os.environ.get("CUDA_VERSION", default_cuda_version).split("."))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

The issue is that the CPU-only version of Pytorch is installed, where `default_cuda_version=torch.version.cuda` is `None`.  Seems like an upstream issue, but we may need to workaround here.

**Comment by avitial** [comment]
Ref. 138689

**Comment by peterchen-intel** [comment]
@ngaloppo If this issue is still valid?

**Comment by peterchen-intel** [comment]
Close inactive issue.
