### ISSUE TITLE
chatglm3 fails with jsonl input 

### ISSUE THREAD

**Issue by avinashbhat09** [openvinotoolkit/openvino.genai#476]
### Context

when I try to run chatglm3 it fails.
command used:
![image](https://github.com/openvinotoolkit/openvino.genai/assets/98947310/857ad653-62fb-4d81-a180-8ff5c79964e2)

error:
[ ERROR ] An exception occurred
[ INFO ] Traceback (most recent call last):
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\benchmark.py", line 547, in main
    iter_data_list, pretrain_time = CASE_TO_BENCH[model_args['use_case']](model_path, framework, args.device, model_args, args.num_iters)
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\benchmark.py", line 210, in run_text_generation_benchmark
    run_text_generation(input_text, num, model, tokenizer, args, iter_data_list, warmup_md5, prompt_idx, bench_hook, model_precision, proc_id)
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\benchmark.py", line 107, in run_text_generation
    result = model.generate(**input_data, max_new_tokens=int(max_gen_tokens), num_beams=args['num_beams'], use_cache=True, eos_token_id=None)
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\python-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\python-env\lib\site-packages\optimum\intel\openvino\modeling_decoder.py", line 642, in generate
    result = super().generate(
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\python-env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\python-env\lib\site-packages\transformers\generation\utils.py", line 1576, in generate
    result = self._greedy_search(
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\utils\hook_greedy_search.py", line 234, in new_greedy_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "C:\Users\Local_Admin\openvino.genai\llm_bench\python\utils\ov_model_classes.py", line 311, in prepare_inputs_for_generation
    mask_positions.append(seq.index(tmp_mask_token))
ValueError: 130000 is not in list

### What needs to be done?

not sure

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers
- [How to link your Pull Request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

### Contact points

NA

**Comment by avinashbhat09** [comment]
[chatGLM. error.txt](https://github.com/user-attachments/files/15613594/chatGLM.error.txt)

**Comment by avinashbhat09** [comment]
Issue is seen with simple prompts as well  (-p) cli

**Comment by peterchen-intel** [comment]
@avinashbhat09  If this is same as CVS-136766?

**Comment by avinashbhat09** [comment]
@peterchen-intel : Yes, it looks to be same issue

**Comment by peterchen-intel** [comment]
@avinashbhat09 Can you please provide one details
openvino.genai commit id
hugging face model commit ID or how you get the IR model?
conversion command line

**Comment by wgzintel** [comment]
@avinashbhat09 
genai commit id: 5562025d83 (master)
openvino: 4fcfaf24b30
chatglm3 can run successfully on both CPU and dGPU
[chatglm3_run_on_dGPU.txt](https://github.com/user-attachments/files/15833087/chatglm3_run_on_dGPU.txt)
[chatglm3_run_on_CPU.txt](https://github.com/user-attachments/files/15833088/chatglm3_run_on_CPU.txt)

**Comment by peterchen-intel** [comment]
@avinashbhat09 We can't reproduce it. Can you try with updated openvino.genai?

**Comment by avinashbhat09** [comment]
Hi, we can close this ticket. Issue not seen with below commit
genai commit id: https://github.com/openvinotoolkit/openvino.genai/commit/5562025d83ebc2264e47134008bd10d9218d98b2 (master)
openvino: 4fcfaf24b30 (master)
