### ISSUE TITLE
cannot generate models for cpp sample.

### ISSUE THREAD

**Issue by xczhai** [openvinotoolkit/openvino.genai#635]
When run `optimum-cli export openvino --trust-remote-code --model TinyLlama/TinyLlama-1.1B-Chat-v1.0 TinyLlama-1.1B-Chat-v1.0` locally, it reports like:
```bash
Traceback (most recent call last):
  File "//workspace/llm_dev/venv/llm/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
  File "//workspace/llm_dev/venv/llm/lib/python3.10/site-packages/optimum/commands/optimum_cli.py", line 163, in main
    service.run()
  File "//workspace/llm_dev/venv/llm/lib/python3.10/site-packages/optimum/commands/export/openvino.py", line 310, in run
    task = infer_task(self.args.task, self.args.model)
  File "//workspace/llm_dev/venv/llm/lib/python3.10/site-packages/optimum/exporters/openvino/__main__.py", line 51, in infer_task
    task = TasksManager.infer_task_from_model(model_name_or_path)
  File "//workspace/llm_dev/venv/llm/lib/python3.10/site-packages/optimum/exporters/tasks.py", line 1668, in infer_task_from_model
    task = cls._infer_task_from_model_name_or_path(model, subfolder=subfolder, revision=revision)
  File "//workspace/llm_dev/venv/llm/lib/python3.10/site-packages/optimum/exporters/tasks.py", line 1581, in _infer_task_from_model_name_or_path
    raise RuntimeError(
RuntimeError: Cannot infer the task from a local directory yet, please specify the task manually (masked-im, question-answering, image-to-image, zero-shot-object-detection, feature-extraction, object-detection, automatic-speech-recognition, text-generation, token-classification, audio-xvector, stable-diffusion-xl, text-classification, depth-estimation, audio-frame-classification, image-classification, mask-generation, image-to-text, text-to-audio, stable-diffusion, image-segmentation, fill-mask, multiple-choice, sentence-similarity, audio-classification, text2text-generation, zero-shot-image-classification, conversational, semantic-segmentation).
```

**Comment by Wovchena** [comment]
You have `TinyLlama` folder which contains incomplete model. Remove or rename it

**Comment by xczhai** [comment]
I checked the SHA256. They are same.

**Comment by xczhai** [comment]
`sha256sum filename`

**Comment by xczhai** [comment]
- `--task text-generation-with-past --weight-format fp16` can resolve the issue.
- I am not sure that this issue occurs on other models. If so, the doc readme may need a refresh.
