### ISSUE TITLE
Failed to Run Benchmark for stable-diffusion-xl-base-1.0

### ISSUE THREAD

**Issue by ravi9** [openvinotoolkit/openvino.genai#909]
```bash
$ python convert.py --model_id stabilityai/stable-diffusion-xl-base-1.0 --precision FP16 --output_dir ../models/sdxl

$ python benchmark.py -m ../models/sdxl/pytorch/dldt/FP16

[ INFO ] ==SUCCESS FOUND==: use_case: image_gen, model_type: sdxl
[ INFO ] OV Config={'CACHE_DIR': ''}
[ INFO ] OPENVINO_TORCH_BACKEND_DEVICE=CPU
[ INFO ] Model path=../models/sdxl/pytorch/dldt/FP16, openvino runtime version: 2024.4.0-16579-c3152d32c9c-releases/2024/4

Compiling the vae_decoder to CPU ...
Compiling the unet to CPU ...
Compiling the text_encoder_2 to CPU ...
Compiling the text_encoder to CPU ...
Compiling the vae_encoder to CPU ...
[ INFO ] From pretrained time: 4.46s
[ INFO ] Benchmarking iter nums(exclude warm-up): 0, prompt nums: 1, prompt idx: [0]
[ INFO ] [warm-up] Input params: Batch_size=1, steps=20, width=512, height=512, guidance_scale=None
[ ERROR ] An exception occurred
[ INFO ] Traceback (most recent call last):
  File "/home/ravi/projects/openvino.genai/llm_bench/python/benchmark.py", line 857, in main
    iter_data_list, pretrain_time = CASE_TO_BENCH[model_args['use_case']](model_path, framework, args.device, model_args, args.num_iters)
  File "/home/ravi/projects/openvino.genai/llm_bench/python/benchmark.py", line 566, in run_image_generation_benchmark
    run_image_generation(image_param, num, prompt_idx_list[image_id], pipe, args, iter_data_list, proc_id)
  File "/home/ravi/projects/openvino.genai/llm_bench/python/benchmark.py", line 502, in run_image_generation
    res = pipe(input_text_list, num_inference_steps=nsteps, height=image_height, width=image_width, **additional_args).images
  File "/home/ravi/pyenvs/ov-genai-env/lib/python3.10/site-packages/optimum/intel/openvino/modeling_diffusion.py", line 961, in __call__
    return StableDiffusionXLPipelineMixin.__call__(
  File "/home/ravi/pyenvs/ov-genai-env/lib/python3.10/site-packages/optimum/pipelines/diffusers/pipeline_stable_diffusion_xl.py", line 402, in __call__
    ) = self._encode_prompt(
  File "/home/ravi/pyenvs/ov-genai-env/lib/python3.10/site-packages/optimum/pipelines/diffusers/pipeline_stable_diffusion_xl.py", line 117, in _encode_prompt
    prompt_embeds = np.concatenate(prompt_embeds_list, axis=-1)
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
```

Package versions:
- diffusers==0.30.3
- optimum==1.22.0
- optimum-intel==1.20.0.dev0+f34bd61
- openvino==2024.4.0
- torch==2.4.1+cpu

**Comment by ravi9** [comment]
`convert.py` is deprecated and should not be used.
The way to export to openvino format is using `optimum-cli`
```bash
optimum-cli export openvino --model stabilityai/stable-diffusion-xl-base-1.0 --weight-format fp16  ../models/sdxl-fp16

python benchmark.py -m ../models/sdxl-fp16/ 
```

Thank you @andrei-kochin for the recommendation.

**Comment by andrei-kochin** [comment]
Thanks to @eaidova pointing me to this known limitation!

Will state explicitly in the convert.py that is not for production use.
